### PR TITLE
as/master rebase on master

### LINKED ISSUE #11: Merge Upstream Changes
Need to merge changes from the upstream repo into `master`, then into `as/master`.

### PR DESCRIPTION
**Pull request by JWhitleyWork**
Rebases `as/master` on `master` (current version from `autowarefoundation`) to alleviate some conflicts that would be caused with a merge commit.

Closes #11 

This will likely be run again post-1.12 release.

### CODE REVIEW

**Comment by JWhitleyWork** [comment]
Found a problem locally and want to add Melodic build to CI.

**Comment by icolwell-as** [comment]
What does this PR do that #8 doesn't?

**Comment by JWhitleyWork** [comment]
#8 is a merge - this is a rebase. This also includes newer commits than #8. Rebasing first keeps us from having conflicts in the resultant PR and keeps *our* history cleaner.

**Comment by icolwell-as** [comment]
Any GitHub PR can be a merge, squash, or rebase, the only difference is the drop-down you select at the bottom (see the arrow next to "Squash and merge". I'm just confused why the `as/master_rebase` branch needs to exist.

**Comment by JWhitleyWork** [comment]
@icolwell-as - You're right. I'm closing this in favor of one on the new Gitlab fork anyway. Thanks.

**Pull request closed without merging**
