### PR TITLE
Update robosense submodule

### PR DESCRIPTION
**Pull request by icolwell-as**
We don't even use this driver, but I'm updating the submodule because a newer version fixes the CMakeLists file so that we don't get xml errors everytime we launch something.

Testing:
Please build this branch and confirm the xml errors are gone when launching anything.

### CODE REVIEW

**Comment by JWhitleyAStuff** [comment]
Would it make more sense to make this a submodule rather than copying the code so it is more easily updated in the future?

**Comment by snehagn** [comment]
This is already a submodule, if I am not mistaken:

git submodule status
-da97879fb78e1df3b84a60572d90faa6aea4189b ../../../../../../../msgs/lgsvl_msgs
-ac1dbaef89b8e1464642f362af6593f67a42af7b ../../../../../../../sensing/drivers/lidar/packages/ouster
-038e5f6524305d0d287805fdc9029872627ac7de ../../../../../../../sensing/drivers/lidar/packages/robosense
-e364448fad421cb6244c9f828f978d8d877dcbf9 ../../../../../../../simulation/gazebo_simulator/worlds/external/car_demo
-53b8483d098999298498854f3795a9f01c5e8828 ../../../../../../../simulation/gazebo_simulator/worlds/external/osrf_citysim

**Comment by icolwell-as** [comment]
@JWhitleyAStuff, as @snehagn mentioned, it is a submodule, all I did was update the submodule pointer.

**Comment by JWhitleyAStuff** [comment]
Nevermind. It was hard to tell on mobile. LGTM.

**Pull request merged**
