### PR TITLE
Update as/master with master 

### PR DESCRIPTION
**Pull request by icolwell-as**
This PR updates our `as/master` branch with changes from autoware's `master`. There seemed to be some commits to the master branch after the release of 1.11 (which we branched from) which probably should have been included in the 1.11 release. 
Anyway, one benefit of updating is the new vehicle_description package with a lexus model. 

Not sure why the commit history is such a mess (maybe [this PR](https://github.com/autowarefoundation/autoware/pull/2140)?)

Merge PR #9 to resolve conflict.

### CODE REVIEW

**Comment by JWhitleyAStuff** [comment]
@icolwell-as - I'm fine with keeping `as/master` close to `master`. However, this PR removes our CI config script (.circleci/config.yml) which is why it is failing. Also, we need to discuss our strategy with regard to this branch before this is merged because our team has been installing `as/master` on customer vehicles and there is no real versioning going on here for them to pin to.

**Comment by shan-as** [comment]
I'm with Josh. We should have a discussion on whether or not we keep chasing a moving target for these changes.

**Comment by icolwell-as** [comment]
This PR isn't deleting the circleCI config, I think circleCI is just confused because the master branch has no config, but the as/master branch does.
This is weird if it is supposed to be building PRs, shouldn't it start from the PR base branch (as/master) and then merge in the PR branch (master) before doing a CI test? Not sure why CircleCI would have a hard time with this.

In terms of installing this fork on customer vehicles, we discussed the existence of a `as/release` branch. I thought the general idea was to develop on master and only really give customers the `as/release` branch. The PRs into `as/release` would require more rigorous testing such as mandatory sim testing, vehicle testing, etc. I agree though, we should have a discussion on how this should roll out.

@shan-as I don't think we have any option other than keeping up with autoware. It would likely be too much work to selectively evaluate what parts of autoware we want to use.

**Comment by JWhitleyAStuff** [comment]
@icolwell-as The CI isn't working because the source branch doesn't have it. I was wrong.

Shouldn't this be a rebase instead of a merge? It shouldn't be that bad since we only added the `feature/deadreckoner` branch to `as/master`.

And you're probably right about `as/release`. I'll create it at the commit where I added CI to this branch. Everything before that is tested and has been customer-installed.

**Comment by icolwell-as** [comment]
I think you can choose rebase in the drop-down merge button when the time comes to merge/rebase the PR. In general, yes, I would agree with rebase, but this merge in particular is a little messy (commits dating back to Nov. 2018 somehow), so it might be cleaner to squash this until autoware master starts having a cleaner history.

**Review by JWhitleyWork — APPROVED** [review]

**Pull request closed without merging**
